call plug#begin('~/.config/nvim/bundle')
Plug 'morhetz/gruvbox' 
Plug 'scrooloose/nerdtree' 
Plug 'kien/ctrlp.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-surround'
Plug 'easymotion/vim-easymotion'
call plug#end()
colorscheme gruvbox
